### ISSUE TITLE
Operations manipulating Buffer Indexes are not atomic and therefore prone to Race conditions

### ISSUE THREAD

**Issue by pramilo** [andygock/avr-uart#11]
I've come across this issue while debugging the other issue I posted.

The problem is that the Indexes for the circular buffer are manipulated in functions that are outside the Interrupts and are also manipulated inside the interrupts.

Calculations such as:
tmphead  = (UART_TxHead + 1) & UART_TX_BUFFER_MASK;

are very dangerous and prone to errors caused by race conditions.

In particular when this code is compiled and ran it is broken down into a fetch of UART TX Head to a register and then an addition and then a bitwise operation.

The potential risk here, is having the interrupt fire after UART TX Head has been pulled to a register for caulcation and before the calculation is complete, an interrupt firing that halts processing of the main code, changes the value of UART Tx Head and returning.

At this point, the UART TX Head has changed value as a result of the interrupt.

However in the main code thread, UART TX Head is not re-read; it had already been read into a register. All further calculations will be done using a value that is outdated and will cause un wanted behaviour.

The correct way to do it, would be enclose all atomic calculations done in main code (not interrupts) in an "ATOMIC_BLOCK(ATOMIC_FORCEON)".

For example, the above code, should become:
ATOMIC_BLOCK(ATOMIC_FORCEON) {
	tmphead  = (UART_TxHead + 1) & UART_TX_BUFFER_MASK;
}
to ensure the operation is performed atomically and that the value of UART TX Head is guaranteed to be the correct one.

This happens in several parts of the code so a code revision would be advisable.

ATOMIC_BLOCK is supported by including  "util/atomic.h"

Thank you

**Comment by andygock** [comment]
@pramilo Thanks for pointing that out. You're right. I'll update the codebase with this protection once I get some time to have a look at it.

**Comment by andygock** [comment]
Code revised in merge 6773f425747eae3cecd49c28cf8c440f18b4ea99
