### ISSUE TITLE
calculate buffer index in ISRs, *_getc() a.s.o.

### ISSUE THREAD

**Issue by ScharffenbergFrank** [andygock/avr-uart#12]
Hi,  
should not it be a modulo operation here?  

`tmphead = (UART_RxHead + 1) & UART_RX0_BUFFER_MASK;  `

Kind regards, Frank

**Comment by andygock** [comment]
It has the same outcome I believe.

Actually, if only 8-bit buffer compatibility was needed, just `tmphead = UART_RxHead + 1` on its own would work, as a modulo result is automatic due to the "wrap around" of the `+1` operation once it `tmphead` reaches 255.
