### ISSUE TITLE
Atomic operations should use ATOMIC_RESTORESTATE

### ISSUE THREAD

**Issue by clnhlzmn** [andygock/avr-uart#13]
Would it not be better to use `ATOMIC_RESTORESTATE`? As in:

    ATOMIC_BLOCK(ATOMIC_RESTORESTATE) {
        //do things atomically
    }

This would avoid enabling interrupts when a user doesn't expect them to be on. I understand that the library requires interrupts, but maybe there are cases when the user has interrupts disabled and still wants to interact with the library in some way.

**Comment by andygock** [comment]
I'm a bit late with this. Thanks @smdjeff  for the pull request. Fixed in [40e5f30](https://github.com/andygock/avr-uart/commit/40e5f306ef48738a64c122886fe781bf5ee96492).
