### ISSUE TITLE
When USART0 is not enabled compile fails

### ISSUE THREAD

**Issue by silverki** [andygock/avr-uart#9]
When `#define USART0_ENABLED` is commented out in `uart.h` following compilation error occurs:

```
uart.c:513:17: error: 'UART_RxHead' undeclared (first use in this function)
     tmphead = ( UART_RxHead + 1) & UART_RX0_BUFFER_MASK;
                 ^

```

Problem can be solved with adding preprocessor definitions to exclude all UART0 functions.

directly before line 484 add `#if defined( USART0_ENABLED )`

and

directly after line 757 add `#endif /* defined( USART0_ENABLED ) */`

**Comment by andygock** [comment]
Thank you.

Already fixed in latest release 6773f425747eae3cecd49c28cf8c440f18b4ea99
